parameters:
  - name: backend_config
    type: object
    displayName: Backend Config
    default:
      null
  - name: azure_subscription_id
    type: string
    displayName: Azure Subscription ID
  - name: migrate_backend
    type: boolean
    displayName: Migrate Backend?
    default: false
  - name: task_name
    type: string
    displayName: Task Name
    default: 'tf_init'
  - name: working_directory
    type: string
    displayName: Working Directory
    default: '$(Build.SourcesDirectory)'

steps:
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: '$(Build.SourcesDirectory)/scripts/terraform/init.ps1'
      arguments: >
        -backend_config ${{ convertToJson(parameters.backend_config) }}
        -azure_subscription_id ${{ parameters.azure_subscription_id }}
        -migrate_backend ${{ parameters.migrate_backend }}
      workingDirectory: '${{ parameters.working_directory }}'
    displayName: terraform init