parameters:
  - name: backend_config
    type: object
    displayName: Backend Config
    default:
  - name: backend
    type: boolean
    displayName: Backend?
    default: true
  - name: migrate_backend
    type: boolean
    displayName: Migrate Backend?
    default: false
  - name: task_name
    type: string
    displayName: Task Name
    default: 'tf_init'
  - name: working_directory
    type: string
    displayName: Working Directory
    default: '$(Build.SourcesDirectory)'

steps:
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: '$(Build.SourcesDirectory)/scripts/tf/init.ps1'
      pwsh: true
      ${{ if eq(length(parameters.backend_config), 0) }}:
        arguments: >
          -terraform_migrate $${{ parameters.migrate_backend }}
          -terraform_backend $${{ parameters.backend }}
      ${{ if ge(length(parameters.backend_config), 1) }}:
        arguments: >
          -terraform_migrate $${{ parameters.migrate_backend }}
          -terraform_backend_config ${{ parameters.backend_config }}
          -terraform_backend $${{ parameters.backend }}
      workingDirectory: '${{ parameters.working_directory }}'
    ${{ if eq(parameters.migrate_backend, true) }}:
      displayName: terraform migrate
    ${{ if eq(parameters.migrate_backend, false) }}:
      displayName: terraform init