parameters:
- name: working_directory
  type: string
  default: '$(Build.SourcesDirectory)'
  displayName: Working Directory
- name: state_file
  type: string
  displayName: State File
  default: 'terraform.tfbackend'
- name: output_folder
  type: string
  displayName: Output Folder
  default: "$(Build.SourcesDirectory)/variables"

steps:
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: '$(Build.SourcesDirectory)/scripts/utils/create_state_file.ps1'
      workingDirectory: ${{ parameters.working_directory }}
      arguments: >
        -terraform_plan_file "${{ parameters.state_file }}"
        -output_folder "${{ parameters.output_folder }}"
        -cicd_ado $true
    displayName: Create ${{ parameters.state_file }}