parameters:
- name: working_directory
  type: string
  default: '$(Build.SourcesDirectory)'
  displayName: Working Directory

steps:
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: '$(Build.SourcesDirectory)/scripts/utils/remove_backend.ps1'
      workingDirectory: ${{ parameters.working_directory }}
    displayName: Remove backend.tf