parameters:
  - name: duration
    type: number
  - name: message
    type: string
    default: 'Sleeping'
  - name: display_name
    type: string
    default: ''

variables:
  - name: sleep_display_name
    value: coalesce(parameters.display_name, 'Sleep for ${{ parameters.duration }} seconds')

steps:
  - task: PowerShell@2
    displayName: ${{ parameters.sleep_display_name }}
    inputs:
      targetType: 'inline'
      script: |
        Write-Verbose "${{ parameters.message }}" -Verbose
        Start-Sleep -Seconds ${{ parameters.duration }}