parameters:
- name: service_connection
  type: string
  displayName: Service Connection To Use
- name: skip
  type: boolean
  default: false
  displayName: Skip ADO Checks?
- name: ado_org
  type: string
  displayName: Azure DevOps Org Name
- name: ado_project
  type: string
  displayName: Azure DevOps Project Name

steps:
  - ${{ if eq(parameters.skip, false) }}:
    - task: AzureCLI@2
      name: ado_check
      inputs:
        azureSubscription: ${{ parameters.service_connection }}
        scriptType: pscore
        scriptLocation: scriptPath
        scriptPath: ./scripts/check_ado.ps1
        arguments: >
          -ado_project ${{ parameters.ado_project }}
          -ado_org ${{ parameters.ado_org }}
          -service_connection ${{ parameters.service_connection }}