parameters:
  - name: service_connection
    type: string
    displayName: Service Connection To Use
    default: ''
  - name: managed_identity
    type: boolean
    displayName: Managed Identity?
    default: false
  - name: task_name
    type: string
    displayName: Task Name
    default: 'az_login'

steps:
  - ${{ if eq(parameters.managed_identity, false) }}:
    - task: AzureCLI@2
      ${{ if eq(parameters['task_name'], 'az_login') }}:
        name: az_login
      ${{ else }}:
        name: az_login_${{ parameters['task_name'] }}
      inputs:
        azureSubscription: ${{ parameters.service_connection }}
        addSpnToEnvironment: true
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          $env | ForEach-Object { Write-Verbose $_  -Verbose }
          # Translate Service Connection Environment Variables to Terrraform Environment Variables
          Write-Host "##vso[task.setvariable variable=ARM_CLIENT_ID;]$($env:ARM_CLIENT_ID)"
          Write-Host "##vso[task.setvariable variable=ARM_CLIENT_SECRET;issecret=true;]$($env:servicePrincipalKey)"
          Write-Host "##vso[task.setvariable variable=ARM_TENANT_ID;]$($env:tenantId)"
      displayName: az login
  - task: PowerShell@2
    ${{ if eq(parameters['task_name'], 'az_login') }}:
      name: az_login_mi
    ${{ else }}:
      name: az_login_${{ parameters['task_name'] }}
    inputs:
      targetType: 'filePath'
      filePath: '$(Build.SourcesDirectory)/scripts/az/login.ps1'
      arguments: >
        -managed_identity $${{ parameters.managed_identity }}
      workingDirectory: '$(Build.SourcesDirectory)'
    displayName: az login identity
    env:
      ARM_CLIENT_ID: $(ARM_CLIENT_ID)
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_TENANT_ID: $(ARM_TENANT_ID)