parameters:
- name: service_connection
  type: string
  displayName: Service Connection To Use
- name: graph_permission
  type: string
  displayName: Graph Permission To Check

steps:
  - task: AzureCLI@2
    name: entra_check
    inputs:
      azureSubscription: ${{ parameters.service_connection }}
      displayName: ${{ parameters.graph_permission }}
      addSpnToEnvironment: true
      scriptType: pscore
      scriptLocation: scriptPath
      scriptPath: '$(Build.SourcesDirectory)/scripts/entra/get_approle.ps1'
      workingDirectory: '$(Build.SourcesDirectory)/scripts/entra'
      arguments: >
        -object_id "8dc8ef1c-07a4-4303-975b-d72f005df0c3"
        -graph_permission ${{ parameters.graph_permission }}