pool:
  vmImage: ubuntu-latest

parameters:
  - name: service_connection
    type: string
    displayName: Service Connection To Use
    default: lmsp0

stages:
- stage: check_ado
  displayName: Check ADO
  jobs:
  - job: tf_init
    displayName: terraform plan
    steps:
      - template: templates/utils/cloud_init.yaml
      - checkout: self
        persistCredentials: true
      - template: templates/utils/remove_backend.yaml
      - template: templates/az/login.yaml
        parameters:
          service_connection: ${{ parameters.service_connection }}
      - template: templates/tf/init.yaml
        parameters:
          azure_subscription_id: 3f96fd38-eec2-48f5-8d76-c9b6c17c8c95
          working_directory: '$(Build.SourcesDirectory)/terraform'

      