pool:
  vmImage: ubuntu-latest

parameters:
  - name: service_connection
    type: string
    displayName: Service Connection To Use
  - name: ado_service_connection
    type: string
    default: ''
    displayName: (Optional) ADO Service Connection To Use
  - name: ado_agent_pool_vmss_id
    type: string
    displayName: Azure VMSS ID
  - name: ado_service_connection_name
    type: string
    displayName: New ADO Service Connection Name
  - name: ado_agent_pool_name
    type: string
    displayName: New ADO Agent Pool Name
  - name: subscription_name
    type: string
    displayName: Subscription Name (for new ADO Service Connection)
  - name: skip_checks
    type: boolean
    default: false
    displayName: Skip ADO Checks?

steps:
  - template: templates/check_ado.yaml
    parameters:
      service_connection: ${{ coalesce(parameters.ado_service_connection, parameters.service_connection) }}
      skip: ${{ parameters.skip_checks }}
  - template: templates/register_agent.yaml
    parameters:
      ado_service_connection: ${{ parameters.ado_service_connection }}
      ado_service_connection_name: ${{ parameters.endpoint_name }}
      ado_agent_pool_name: ${{ parameters.ado_agent_pool_name }}
      ado_agent_pool_vmss_id: ${{ parameters.azure_vmss_id }}
      service_connection: ${{ parameters.service_connection }}
      subscription_name: ${{ parameters.subscription_name }}